### ISSUE TITLE
Exception when invoking com.criteo.marketing.api.CampaignApi.getAdSet(String)

### ISSUE THREAD

**Issue by asiemsuk** [criteo/criteo-java-marketing-transition-sdk#1]
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 10 path $.data
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.criteo.marketing.JSON.deserialize(JSON.java:138)
	at com.criteo.marketing.ApiClient.deserialize(ApiClient.java:806)
	at com.criteo.marketing.ApiClient.handleResponse(ApiClient.java:1009)
	at com.criteo.marketing.ApiClient.execute(ApiClient.java:936)
	at com.criteo.marketing.api.CampaignApi.getAdSetWithHttpInfo(CampaignApi.java:160)
	at com.criteo.marketing.api.CampaignApi.getAdSet(CampaignApi.java:139)

Attribute "data" of com.criteo.marketing.model.ResponseReadAdSet is NOT a list

**Comment by jbuisson-criteo** [comment]
Thanks for your issue @asiemsuk, we fixed it in #2
